### ISSUE TITLE
开源版本3.7.0升级到3.7.1不应该报错

### ISSUE THREAD

**Issue by hoganlxj** [yunionio/ocboot#102]
![image](https://user-images.githubusercontent.com/32036395/118930064-dcb49100-b977-11eb-91e0-b9d5fb13741a.png)

**Comment by zexi** [comment]
是不是升级过程中网络断了？

**Comment by hoganlxj** [comment]
升级过程，网络没有中断

**Comment by zexi** [comment]
根据 https://github.com/ansible/ansible/issues/17349 来看，我试试把 ssh connect 的 timeout 调高点再试试。

**Comment by zexi** [comment]
https://github.com/yunionio/ocboot/pull/103
