### ISSUE TITLE
 ansible 的脚本缺一个更换内核以后重启的步骤

### ISSUE THREAD

**Issue by zexi** [yunionio/ocboot#24]
如果待部署的节点角色设置为 “as_host: true" 的话，会部署 onecloud 的私有云计算节点的内核，需要重启让内核生效。

```bash
# 重启前
$ uname -a
Linux Master01-10-127-248-1 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# 重启后
$ uname -a
Linux lzx-oc-node 3.10.0-1062.4.3.el7.yn20191203.x86_64 #1 SMP Tue Dec 3 15:53:43 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

虽然目前文档里面　https://docs.yunion.io/docs/quickstart/allinone/#1-%E5%9C%A8-all-in-one-%E4%B8%AD%E6%89%BE%E4%B8%8D%E5%88%B0%E8%99%9A%E6%8B%9F%E6%9C%BA%E7%95%8C%E9%9D%A2
有说，但还是需要从根本上解决下这个情况

**Comment by WangAnge** [comment]
有一个问题， 比如原来keepalived 监听eth0 或者 bond0, 装完以后， 全变成br0 了， 重启keepalived 会失败,

**Comment by zexi** [comment]
PR: https://github.com/yunionio/ocboot/pull/98 添加了重启的逻辑。

keepalived 需要能根据 br0 的添加，变更配置，这个还需要优化。
