### ISSUE TITLE
config-example-allinone.yml  onecloud_version 希望能更新

### ISSUE THREAD

**Issue by dblife1024** [yunionio/ocboot#264]
config-example-allinone.yml  onecloud_version 希望能更新，另外，希望可以增加./ocboot.py -v 参数

**Comment by zexi** [comment]
> config-example-allinone.yml onecloud_version 希望能更新，另外，希望可以增加./ocboot.py -v 参数

更新的话需要单独用 upgrade 命令，参考：https://github.com/yunionio/ocboot#%E5%8D%87%E7%BA%A7%E8%8A%82%E7%82%B9

另外 `-v` 的参数是表达什么含义？显示版本号吗？
